### ISSUE TITLE
CSS垂直中央寄せが機能しない - 枠線・ハイライトブロック内のテキスト配置問題

### ISSUE THREAD

**Issue by mo9mo9-uwu-mo9mo9** [mo9mo9-uwu-mo9mo9/Kumihan-Formatter#103]
## 問題概要

枠線・ハイライトブロック内のテキストが垂直中央寄せされず、上部に配置される問題が発生しています。

## 期待する動作

- テキストは**水平左寄せ + 垂直中央寄せ**で表示されるべき
- 枠線・ハイライトブロックの高さに関係なく、テキストが垂直方向の中央に配置される

## 現在の動作

- テキストが上部に配置されている
- 垂直中央寄せのCSSが適用されていない

## 影響範囲

- `.box`（枠線ブロック）
- `.highlight`（ハイライトブロック）
- 複合キーワードによるネスト構造

## 確認済み箇所

以下のCSSが設定されているが、効果が発揮されていない：

```css
.box {
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 60px;
}

.highlight {
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 60px;
}
```

## 再現手順

1. `test_patterns.txt`をHTML変換
2. 生成されたHTMLをブラウザで表示
3. 枠線・ハイライトブロック内のテキスト配置を確認

## 環境

- 対象ファイル: `kumihan_formatter/templates/base.html.j2`
- ブラウザ: Safari (macOS)
- 緊急度: 高（レイアウト基本機能）

## 添付画像

問題を示すスクリーンショットを添付します。

## 優先度

- **緊急**: レイアウトの基本機能に影響
- ユーザー体験に直接関わる視覚的問題
