### ISSUE TITLE
【着手順④低優先】テーマ機能の実装：セピア・ダーク・ハイコントラスト等の多彩なテーマ対応

### ISSUE THREAD

**Issue by mo9mo9-uwu-mo9mo9** [mo9mo9-uwu-mo9mo9/Kumihan-Formatter#114]
## 🎨 機能提案

Kumihan-Formatterの出力HTMLに複数のテーマ機能を追加し、ユーザーが好みのカラーテーマを選択できるようにする。

#### 基本テーマ
- **デフォルト**: 現在の白ベーステーマ
- **ダーク**: 黒背景・白文字の目に優しいテーマ
- **セピア**: レトロな茶色系テーマ（書籍風）

#### アクセシビリティテーマ
- **ハイコントラスト**: 視認性を重視した高コントラストテーマ
- **大きめフォント**: 高齢者向け大きめフォントテーマ

#### Option 1: CSS変数ベース
- CSS変数を使った動的テーマ切り替え
- JavaScript制御で瞬時切り替え
- ローカルストレージでテーマ記憶

#### Option 2: 複数CSS提供
- テーマ別CSSファイルを用意
- CLI実行時にテーマ選択オプション
- 静的HTML生成（JavaScript不要）

### 💡 推奨実装

**Option 2（複数CSS提供）**を推奨：
- ✅ JavaScript不要でシンプル
- ✅ 配布HTMLが軽量
- ✅ オフライン環境でも完全動作

#### CLI拡張
```bash
# テーマ指定での変換
python -m kumihan_formatter input.txt --theme dark
python -m kumihan_formatter input.txt --theme sepia

# 複数テーマ同時生成
python -m kumihan_formatter input.txt --themes default,dark,sepia
```

#### 設定ファイル対応
```yaml
# config.yaml
theme:
  default: default
  available: [default, dark, sepia, high-contrast]
  colors:
    dark:
      background: '#1e1e1e'
      text: '#ffffff'
      accent: '#569cd6'
```

### 📋 実装タスク

- [ ] テーマ用CSSテンプレート作成
- [ ] CLI テーマオプション追加
- [ ] 設定ファイル拡張
- [ ] テーマプレビュー機能
- [ ] ドキュメント更新

### 🎉 期待される効果

1. **アクセシビリティ向上**: 様々なユーザーニーズに対応
2. **ユーザー体験向上**: 好みに応じたテーマ選択
3. **プロダクト差別化**: 他ツールにない多彩なテーマ
4. **用途拡大**: 異なる場面での使い分け可能

**優先度**: Medium  
**対象マイルストーン**: v0.4.0 (UI改善)
