### ISSUE TITLE
🚀 v1.0.0正式公開に向けたリリース仕組みの構築

### ISSUE THREAD

**Issue by mo9mo9-uwu-mo9mo9** [mo9mo9-uwu-mo9mo9/Kumihan-Formatter#127]
## 概要
v1.0.0の正式公開が見えてきた現在、プロフェッショナルなリリースプロセスを確立する必要があります。
現状の手動リリースから、自動化されたCI/CDパイプラインへの移行を提案します。

### 📊 現在の仕組み
- **バージョン管理**: bumpversionツール設定済み（pyproject.toml）
- **変更履歴**: CHANGELOG.md（Keep a Changelogフォーマット）
- **CI/CD**: GitHub Actions（テスト・ビルドのみ）
- **リリース**: 未実装（GitHub Releasesは未使用）

### 🔍 課題
1. リリースプロセスが手動で属人的
2. GitHub Releasesが活用されていない
3. 配布物（ZIP）の自動生成が未整備
4. リリースノートの自動生成がない

### 1️⃣ リリース準備フェーズ
```bash
# 1. リリースブランチ作成
git checkout -b release/v1.0.0

# 2. バージョン更新（自動）
bumpversion minor/major/patch

# 3. CHANGELOG.md更新
# - Unreleasedセクションを新バージョンに移動
# - リリース日付を追加

# 4. PR作成・マージ
```

### 2️⃣ リリース実行フェーズ
```yaml
# .github/workflows/release.yml
name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1. ソースコード取得
      - uses: actions/checkout@v4
      
      # 2. Python環境構築
      - uses: actions/setup-python@v4
      
      # 3. 配布物作成
      - name: Build distribution
        run: |
          pip install -e .
          python -m kumihan_formatter.cli zip-dist . -o release_dist
          
      # 4. リリースノート生成
      - name: Generate release notes
        # CHANGELOG.mdから該当バージョンを抽出
        
      # 5. GitHub Release作成
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release_dist/*.zip
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
```

### 3️⃣ 配布フェーズ
- **GitHub Releases**: ソースコード + 配布用ZIP
- **PyPI**: 将来的に検討（pip installable）
- **Booth**: v1.0.0以降で手動配布

### Phase 1: 基本リリース自動化（v0.4.0まで）
- [ ] release.ymlワークフロー作成
- [ ] リリースノート自動生成スクリプト
- [ ] bumpversionとの連携強化
- [ ] CHANGELOG.md自動更新ツール

### Phase 2: 配布物自動化（v0.9.0まで）
- [ ] Windows/macOS向けZIP自動生成
- [ ] Python環境込みポータブル版作成
- [ ] インストーラー形式の検討
- [ ] 配布物の自動テスト

### Phase 3: 品質保証（v1.0.0）
- [ ] リリース前チェックリスト自動化
- [ ] 破壊的変更の検出
- [ ] 配布物の署名・検証
- [ ] ロールバック手順の確立

### バージョン番号ルール
```
MAJOR.MINOR.PATCH[-PRERELEASE][+BUILD]

例:
- 0.4.0        # 通常リリース
- 0.9.0-beta.1 # ベータ版
- 1.0.0-rc.1   # リリース候補
- 1.0.0        # 正式版
```

### プレリリース戦略
1. **alpha**: 内部テスト（開発者のみ）
2. **beta**: 限定公開テスト（協力者）
3. **rc**: リリース候補（一般公開前）

### 🔍 リリース前確認
- [ ] 全テストがパス
- [ ] ドキュメント更新完了
- [ ] CHANGELOG.md記載完了
- [ ] 破壊的変更の明記
- [ ] サンプルファイル動作確認

### 📦 配布物確認
- [ ] Windows batファイル動作
- [ ] macOS commandファイル動作
- [ ] README.html生成確認
- [ ] 不要ファイル除外確認

### 📢 アナウンス
- [ ] GitHub Release作成
- [ ] リリースノート公開
- [ ] 既知の問題明記
- [ ] アップグレード手順説明

### 開発者視点
- リリース作業の効率化・自動化
- ヒューマンエラーの削減
- 一貫性のあるリリースプロセス

### ユーザー視点
- 安定した品質の配布物
- 明確なリリースノート
- 簡単なダウンロード・インストール

### プロジェクト視点
- プロフェッショナルな印象
- 継続的な改善サイクル
- コミュニティの信頼獲得

## 参考情報
- [Semantic Versioning](https://semver.org/)
- [Keep a Changelog](https://keepachangelog.com/)
- [GitHub Releases](https://docs.github.com/en/repositories/releasing-projects-on-github)
- [Python Packaging Guide](https://packaging.python.org/)

---

**優先度**: 高（v1.0.0正式公開に必須）
**対象マイルストーン**: M7（正式版準備）
**実装開始目標**: v0.4.0から段階的に導入

🤖 Generated with Claude Code
