### ISSUE TITLE
🧪 テストカバレッジ測定・改善の実装

### ISSUE THREAD

**Issue by mo9mo9-uwu-mo9mo9** [mo9mo9-uwu-mo9mo9/Kumihan-Formatter#134]
## 概要
現在のテストの実際のカバレッジを測定し、目標80%以上の高品質なテストスイートを構築します。
抜け漏れの発見と品質保証の強化を行います。

## 背景
現在はテストが存在しますが、どの程度のコードがテストされているかが不明です。
v1.0.0リリースには高い品質保証が必要で、テストカバレッジの可視化と改善が必須です。

### 1. 📊 テストカバレッジ測定の導入

```bash
# pytest-covのインストール
pip install pytest-cov

# カバレッジ測定の実行
pytest --cov=kumihan_formatter --cov-report=html --cov-report=term-missing
```

### 2. 🎯 カバレッジ目標設定

| モジュール | 目標カバレッジ | 重要度 |
|-----------|--------------|-------|
| `parser.py` | 95% | 最高 |
| `renderer.py` | 95% | 最高 |
| `cli.py` | 85% | 高 |
| `config.py` | 90% | 高 |
| `utils/` | 80% | 中 |

### 3. 🔍 カバレッジ分析の自動化

```python
# dev/tools/coverage_analyzer.py
class CoverageAnalyzer:
    def __init__(self):
        self.target_coverage = 80
        
    def analyze(self):
        """カバレッジ分析レポート生成"""
        result = run_coverage()
        
        # 不足している関数を特定
        uncovered_functions = self.find_uncovered_functions()
        
        # 重要度の高い未テスト箇所を特定
        critical_gaps = self.find_critical_gaps()
        
        return CoverageReport(result, uncovered_functions, critical_gaps)
```

### 4. 📈 継続的品質監視

```yaml
# .github/workflows/coverage.yml
name: Coverage Report
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -e .[dev]
          pip install pytest-cov
      
      - name: Run coverage
        run: pytest --cov=kumihan_formatter --cov-report=xml
      
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          
      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
```

#### 予想される不足箇所
1. **エラーハンドリング**
   - 例外的なファイル状況
   - ネットワークエラー
   - 権限エラー

2. **エッジケース**
   - 空ファイル
   - 巨大ファイル
   - 不正な文字コード

3. **プラットフォーム固有処理**
   - Windows/macOS固有の動作
   - パス処理の違い

### 6. 🎨 テストケース生成戦略

```python
# 境界値テストの自動生成
class BoundaryTestGenerator:
    def generate_size_tests(self):
        """ファイルサイズ境界のテスト"""
        return [
            "",  # 空
            "a",  # 1文字
            "a" * 1000,  # 1KB
            "a" * 1000000,  # 1MB
        ]
    
    def generate_encoding_tests(self):
        """エンコーディングテスト"""
        return [
            ("utf-8", "正常なUTF-8"),
            ("shift_jis", "Shift_JIS文字列"),
            ("euc-jp", "EUC-JP文字列"),
        ]
```

### 7. 📋 テスト品質指標

```python
class TestQualityMetrics:
    def calculate_metrics(self):
        return {
            "line_coverage": self.line_coverage(),
            "branch_coverage": self.branch_coverage(),
            "function_coverage": self.function_coverage(),
            "complexity_coverage": self.complexity_coverage(),
        }
    
    def generate_report(self):
        """品質レポート生成"""
        return TestQualityReport(
            coverage=self.calculate_metrics(),
            recommendations=self.get_recommendations(),
            critical_gaps=self.find_critical_gaps()
        )
```

### Phase 1: 基盤構築（1週間）
- [ ] pytest-covの導入と設定
- [ ] CI/CDパイプラインでのカバレッジ測定
- [ ] カバレッジレポートの自動生成

### Phase 2: 分析と改善（2週間）
- [ ] 現在のカバレッジ状況分析
- [ ] 不足テストケースの特定
- [ ] 重要度に基づく優先順位付け

### Phase 3: テスト拡充（2週間）
- [ ] エラーハンドリングテスト追加
- [ ] エッジケーステスト追加
- [ ] 境界値テスト追加

### Phase 4: 品質保証（1週間）
- [ ] カバレッジ目標達成の確認
- [ ] テスト実行時間の最適化
- [ ] ドキュメント更新

## 設定ファイル案

```toml
# pyproject.toml
[tool.coverage.run]
source = ["kumihan_formatter"]
omit = [
    "*/tests/*",
    "*/dev/*",
    "*/__pycache__/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
]
show_missing = true
skip_covered = false

[tool.coverage.html]
directory = "htmlcov"
```

## 成功指標

- **全体カバレッジ80%以上**
- **重要モジュール（parser, renderer）95%以上**
- **ブランチカバレッジ75%以上**
- **テスト実行時間5分以内**

## 品質保証ルール

```python
# dev/tests/test_coverage_requirements.py
def test_minimum_coverage():
    """最低カバレッジ要件のテスト"""
    coverage_data = get_coverage_data()
    
    assert coverage_data.total >= 80, "総合カバレッジが80%未満"
    assert coverage_data.parser >= 95, "parserカバレッジが95%未満"
    assert coverage_data.renderer >= 95, "rendererカバレッジが95%未満"
```

## 優先度
**通常** - 品質保証のための重要な基盤

## 関連Issue
- #128 （v1.0.0リリースタスクリスト）
- #135 （E2Eテストスイート）

---

🤖 Generated with Claude Code
