### ISSUE TITLE
🔧 ツール品質保証の自動化強化：記法チェック精度向上と継続的品質監視の実装

### ISSUE THREAD

**Issue by mo9mo9-uwu-mo9mo9** [mo9mo9-uwu-mo9mo9/Kumihan-Formatter#238]
## 概要
各種ツール（syntax_fixer、テスト、サンプルファイル等）の品質保証を自動化し、記法とテストの整合性エラーを予防する仕組みを強化する。

### 1. 記法チェックの寛容さ問題
```bash
# 明らかな記法エラーサンプルでも「OK」判定
python3 dev/tools/syntax_validator.py 記法ツール/サンプルファイル/記法エラーサンプル.txt
# 結果: [完了] 記法ツール/サンプルファイル/記法エラーサンプル.txt: OK
```

**問題**: 意図的なエラーケースと実際のエラーを区別できず、真の品質問題を見逃す可能性

### 2. 過去の品質問題事例
- **Issue #223**: テンプレートファイルで大量の記法エラー（80個以上）
- **Issue #216**: basic-scenario.txtの変換失敗
- **Issue #158**: 記法ツール実行で85箇所の自動修正が必要
- **E2Eテスト期待値**: 継続的な大幅修正が必要（Issue #207等）

### 3. 手動チェックに依存している領域
- エラーサンプルファイルの真の検証
- 複合キーワードのネスト順序確認
- プラットフォーム固有の動作検証
- パフォーマンス劣化の検出

#### 🔧 厳格モード対応syntax_validator
```python
# 新機能: 検証モード分離
python dev/tools/syntax_validator.py --mode=strict     # 厳格モード
python dev/tools/syntax_validator.py --mode=tolerant   # 寛容モード（現行）
python dev/tools/syntax_validator.py --mode=error-sample # エラーサンプル専用
```

**実装内容**:
- エラーサンプル専用の検証ロジック
- 意図的エラーと実際のエラーの区別
- より厳密な構文チェック（閉じマーカー、属性順序等）

#### 📋 ファイル分類による自動判定
```yaml
# .validation-config.yml
file_patterns:
  strict_mode:
    - "examples/*.txt"
    - "examples/templates/*.txt"
  error_samples:
    - "**/記法エラーサンプル.txt"
    - "**/error-*.txt"
  tolerant_mode:
    - "記法ツール/**/*.txt"
```

#### 📊 品質メトリクス自動監視
```yaml
# .github/workflows/quality-metrics.yml
name: Quality Metrics Monitor
on: [push, pull_request]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Performance Benchmark
        run: |
          # HTMLファイルサイズ監視
          # 変換時間のベンチマーク
          # メモリ使用量の測定
          
      - name: Quality Score
        run: |
          # 記法チェック合格率
          # テストカバレッジ
          # E2Eテスト安定性
```

#### 🎯 品質ゲート設定
```python
# 品質基準の自動チェック
QUALITY_GATES = {
    "syntax_check_pass_rate": 95,      # 記法チェック合格率95%以上
    "conversion_time_limit": 5.0,      # 変換時間5秒以内
    "html_size_growth": 1.2,           # HTMLサイズ増加20%以内
    "test_coverage": 80,               # テストカバレッジ80%以上
}
```

#### 🤖 期待値自動管理
```python
# E2Eテスト期待値の自動更新
def update_expectations_if_valid():
    """品質ゲートを通過した場合のみ期待値を更新"""
    if all_quality_gates_pass():
        update_e2e_expectations()
        create_backup_expectations()
```

#### 🔍 品質劣化の予測と防止
- 変更差分による影響範囲予測
- パフォーマンス劣化の事前検出
- 記法整合性の継続監視

### Week 1: 基盤強化
- [ ] syntax_validator.pyの厳格モード実装
- [ ] ファイル分類設定の導入
- [ ] GitHub Actions品質チェックワークフロー拡張

### Week 2: 監視システム
- [ ] 品質メトリクス収集機能
- [ ] 品質ゲート自動判定
- [ ] アラート通知システム

### Week 3: 統合・最適化
- [ ] E2Eテスト期待値管理改善
- [ ] 品質レポート自動生成
- [ ] 開発者向けダッシュボード

### 開発者の生産性向上
- **手動チェック時間 50%削減**: 自動化による効率化
- **バグ検出の早期化**: CI/CDでの即座な発見
- **品質保証の一貫性**: 人的ミスの排除

### プロジェクト品質向上
- **記法エラーゼロ**: 厳格チェックによる品質確保
- **パフォーマンス安定性**: 継続的監視による劣化防止
- **ユーザー体験向上**: 高品質な出力の保証

### 保守性向上
- **自動的な品質維持**: 手動介入なしでの品質保持
- **予測的保守**: 問題発生前の対応
- **技術的負債削減**: 継続的な品質改善

## 🔄 継続的改善サイクル

```mermaid
graph LR
    A[コード変更] --> B[自動品質チェック]
    B --> C[品質ゲート判定]
    C -->|Pass| D[マージ]
    C -->|Fail| E[修正要求]
    D --> F[品質メトリクス更新]
    F --> G[品質トレンド分析]
    G --> H[改善提案]
    H --> A
```

## 📋 完了条件

- [ ] 記法エラーサンプルが適切に「エラー」判定される
- [ ] 品質メトリクスが自動監視されている
- [ ] E2Eテスト期待値の管理が自動化されている
- [ ] 品質劣化を事前に検出できる
- [ ] 開発者が品質状況を一目で把握できる

## 🏷️ 関連Issue・優先度

**関連**: Issue #228 (構文エラー自動修正), Issue #128 (v1.0.0タスクリスト)
**優先度**: 高（v1.0.0品質保証の要）
**マイルストーン**: v0.4.0 - v0.7.0での段階的実装

この自動化により、Kumihan-Formatterの「人様に渡せる品質」を技術的に保証し、継続的な改善サイクルを確立します。

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>
