### ISSUE TITLE
🎨 UI改善: 枠線内リストマーカー変換・折りたたみブロック装飾強化

### ISSUE THREAD

**Issue by mo9mo9-uwu-mo9mo9** [mo9mo9-uwu-mo9mo9/Kumihan-Formatter#263]
## 🚨 問題の概要
showcase.htmlで以下の表示問題が確認されました：

1. **枠線内リストマーカー問題**: 枠線ブロック内の `- リスト` が `・` に変換されていない
2. **折りたたみブロック視認性**: 折りたたみ機能が地味すぎて気づきにくい

### 問題1: 枠線内リストマーカー変換
**現象**: 
```html
<div class="box">
- <strong>知覚ロール</strong><br>
- 成功：奥から微かな音が聞こえる<br>
- 失敗：特に何も感じない
</div>
```

**期待される結果**:
```html
<div class="box">
<ul>
<li><strong>知覚ロール</strong></li>
<li>成功：奥から微かな音が聞こえる</li>
<li>失敗：特に何も感じない</li>
</ul>
</div>
```

### 問題2: 折りたたみブロック視認性
**現状**: 
- 枠線・背景色は控えめ
- 展開アイコンが小さい
- 折りたたみ機能だと気づきにくい

**期待される改善**:
- より目立つ装飾・色彩
- アイコンの視認性向上
- インタラクティブ感の演出

### 1. パーサー修正（リスト処理）
**ファイル**: `kumihan_formatter/core/block_parser.py`
**問題**: 枠線ブロック内のリスト項目が段落として処理されている

### 2. CSS装飾強化（折りたたみ）
**ファイル**: テンプレートCSS部分
**改善点**:
- より鮮やかな色彩
- ホバー効果の強化
- アイコンサイズの拡大
- アニメーション効果の追加

### 折りたたみブロック装飾強化
```css
/* より目立つ折りたたみスタイル */
details {
    border: 2px solid #007bff;
    background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
    box-shadow: 0 4px 12px rgba(0,123,255,0.15);
}

details summary {
    background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);
    color: white;
    font-weight: bold;
    position: relative;
    padding-left: 3em;
}

details summary::before {
    content: '📂';
    font-size: 1.2em;
    margin-right: 0.5em;
}

details[open] summary::before {
    content: '📁';
}

/* ネタバレ専用スタイル */
details.spoiler summary {
    background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);
}

details.spoiler summary::before {
    content: '⚠️';
}
```

### リスト処理改善
```python
# block_parser.py の改善案
def _parse_block_content(self, content: str) -> str:
    """ブロック内容のリスト項目を適切に処理"""
    lines = content.split('\n')
    processed_lines = []
    
    for line in lines:
        # リスト項目の検出と変換
        if line.strip().startswith('- '):
            # ul/li タグに変換する処理
            pass
```

### ユーザー体験向上
1. **視認性**: 折りたたみ機能が一目で認識可能
2. **操作性**: クリック可能であることが明確
3. **一貫性**: リスト表示の統一性確保

### 表示品質向上
1. **美観**: より洗練された見た目
2. **機能性**: 装飾が機能を伝える
3. **プロ感**: 配布資料としての品質向上

### 修正対象ファイル
- `kumihan_formatter/core/block_parser.py`
- `kumihan_formatter/templates/base.html.j2`
- 既存のHTMLファイル（再生成で対応）

### テスト対象
- 枠線内リスト表示
- 折りたたみ・ネタバレブロック表示
- 既存機能への影響なし

### Phase 1: リスト処理修正
- [ ] block_parser.pyのリスト検出ロジック修正
- [ ] 枠線内リスト項目の適切な変換
- [ ] テストケース追加

### Phase 2: 折りたたみ装飾強化
- [ ] CSSスタイルの大幅改善
- [ ] アイコン・色彩の視認性向上
- [ ] ホバー・アニメーション効果追加

### Phase 3: 検証・調整
- [ ] showcase.html再生成・確認
- [ ] 他サンプルファイルでの動作確認
- [ ] レスポンシブ対応確認

## 📝 優先度

**高** - エンドユーザー向け配布サンプルの表示品質に直結

## 🔗 関連Issue

- Issue #259: showcase.html記法表示トグル（修正済み）
- Issue #119: HTML出力品質の改善（将来課題）

---

同人作家が使用する配布資料の品質向上のため、視覚的な改善を優先実装します。
