### ISSUE TITLE
🚨 CI/CDテスト設計の根本的見直し - pathフィルター最適化と品質保証の両立

### ISSUE THREAD

**Issue by mo9mo9-uwu-mo9mo9** [mo9mo9-uwu-mo9mo9/Kumihan-Formatter#287]
## 🚨 重大な設計問題の発見

PR #286での必須ステータスチェック実行不具合により、**CI/CDテスト設計の根本的な欠陥**を発見しました。

#### **発見した欠陥**
- **PR #286**: ワークフローファイルのみ変更
- **必須テスト**: "Quick Test (Python 3.9)" が**実行されない**
- **原因**: ci.yml の pathフィルターで `ci-full.yml`, `coverage.yml` が除外
- **結果**: GitHub branch protection requirement 違反、マージ不可

#### **設計矛盾の構造**
```
Phase2-2.5最適化の副作用:
1. pathフィルター厳格化 → リソース削減 ✅
2. CI関連ワークフロー変更 → テスト除外 ❌
3. 品質保証の仕組み破綻 → 根本的設計欠陥 🚨
```

#### **1. pathフィルター設計の不整合**
```yaml
# 現在の問題のある設計
ci.yml:
  paths:
    - '.github/workflows/ci.yml'        # ci.yml自体のみ
    # ci-full.yml, coverage.yml は対象外 ← 問題
  
# 必要だった設計  
ci.yml:
  paths:
    - '.github/workflows/ci*.yml'       # CI関連全体
    - '.github/workflows/coverage.yml'  # 品質関連
```

#### **2. テスト階層設計の曖昧さ**
- **必須テスト** vs **オプショナルテスト** の境界が不明確
- **pathフィルター** vs **品質保証** の優先順位が不整合
- **AI開発機動力** vs **テスト品質** のバランス設計不備

#### **3. 依存関係管理の欠如**
- ワークフロー間の相互依存関係が未定義
- CI設定変更時の影響範囲が不明確
- 品質ゲートの継続性が保証されていない

#### **A. テスト階層の明確化**
```
Tier 0: Critical Tests（絶対実行・除外不可）
├── Syntax Check (必須)
├── Import Test (必須)  
└── Quick Test (必須・GitHub branch protection)

Tier 1: Quality Tests（条件付き実行）
├── Coverage Report (ready_for_review時)
├── Integration Test (コア変更時)
└── Performance Test (parser/renderer変更時)

Tier 2: Full Tests（定期・マージ時実行）
├── Full Test Matrix (マージ時)
├── E2E Tests (マージ時)
└── Security Scan (定期実行)
```

#### **B. pathフィルター設計原則**
```yaml
# 新しい設計原則

1. Critical Tests: pathフィルター除外不可
   - 全変更で必ず実行
   - GitHub branch protection との整合性確保

2. Quality Tests: インテリジェント条件分岐
   - 変更規模・影響範囲による自動判定
   - AI開発機動力と品質保証の両立

3. Full Tests: タイミング制御
   - マージ時・定期実行での完全保証
   - リソース効率と品質維持の最適化
```

#### **C. 依存関係管理システム**
```yaml
# ワークフロー依存関係の明確化
dependencies:
  ci.yml:
    triggers_on:
      - 'kumihan_formatter/**'
      - 'dev/tests/**'
      - '.github/workflows/ci*.yml'      # CI関連全体
    never_skip: true                     # 絶対実行
    
  coverage.yml:
    triggers_on:
      - 'kumihan_formatter/**/*.py'
    skip_if:
      - draft_pr: true
      - minor_changes: true
    depends_on: ['ci.yml']               # CI成功後実行
```

#### **Phase 1: 緊急修正（即座実行）**
- [x] ci.yml pathフィルター修正（完了）
- [ ] PR #286のテスト実行確認
- [ ] 他のpathフィルター整合性チェック

#### **Phase 2: 設計再構築（1週間以内）**
- [ ] テスト階層の明確化・実装
- [ ] pathフィルター設計原則の適用
- [ ] ワークフロー依存関係の定義

#### **Phase 3: インテリジェント制御（2週間以内）**
- [ ] 変更影響範囲の自動判定
- [ ] 動的テスト選択システム
- [ ] AI開発最適化との両立

#### **Phase 4: 完全自動化（1ヶ月以内）**
- [ ] 予測的品質管理
- [ ] 自動復旧・代替実行
- [ ] 継続的最適化システム

#### **A. Critical Tests の保護**
```yaml
# ci.yml の新設計
name: CI / Critical Tests (Always Run)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    # pathフィルターなし = 全変更で実行
  workflow_dispatch:

jobs:
  critical-tests:
    name: Critical Tests (Never Skip)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Syntax Check
      - name: Import Test  
      - name: Quick Test
```

#### **B. Quality Tests の条件制御**
```yaml  
# coverage.yml の新設計
name: Coverage / Quality Tests (Conditional)
on:
  pull_request:
    types: [ready_for_review, synchronize]
    paths:
      - 'kumihan_formatter/**/*.py'
      - 'dev/tests/**/*.py'
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-gate:
    name: Quality Gate Check
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.draft == false ||
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch'
```

#### **C. Full Tests の分離**
```yaml
# full-tests.yml の新設計  
name: Full Tests (Merge & Scheduled)
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'  # 毎日2時
  workflow_dispatch:

jobs:
  full-verification:
    name: Full Test Matrix
    # 完全なテストスイート実行
```

#### **品質保証**
- **Critical Tests実行率**: 100%（例外なし）
- **GitHub branch protection**: 完全遵守
- **テスト品質**: 現状維持以上

#### **開発効率**
- **軽微変更時間**: 2-5分以内（Critical Testsのみ）
- **重要変更時間**: 7-15分以内（Quality Tests込み）
- **AI開発機動力**: Phase2.5レベル維持

#### **運用安定性**
- **pathフィルター整合性**: 100%
- **ワークフロー失敗率**: 5%以下
- **予期しないテストスキップ**: 0件

### 🔗 関連Issue・PR

- **Related**: Issue #284 (GitHub Actions最適化)
- **Triggered by**: PR #286 (pathフィルター最適化の副作用)
- **Blocks**: Phase3実装（根本設計修正まで保留）

### 🎯 優先度・緊急度

- **優先度**: **最高** - 品質保証の根幹に関わる
- **緊急度**: **高** - 現在のCI/CD運用に直接影響
- **影響範囲**: 全開発フロー・全PR・全リリース

---

**この根本的見直しにより、pathフィルター最適化とテスト品質保証の完全な両立を実現します。**

🤖 Generated with [Claude Code](https://claude.ai/code)
